/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Latihan2;

/**
 *
 * @author Windows
 */
public class Latiihan2 extends javax.swing.JFrame {

    /**
     * Creates new form Latiihan2
     */
    public Latiihan2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        editnama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        editkelas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        editalamat = new javax.swing.JTextField();
        Buttonproses = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAHasil = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Formulir");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(163, 24, 62, 14);

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 60, 50, 14);

        editnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editnamaActionPerformed(evt);
            }
        });
        getContentPane().add(editnama);
        editnama.setBounds(130, 60, 110, 30);

        jLabel3.setText("Kelas");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 100, 50, 14);

        editkelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editkelasActionPerformed(evt);
            }
        });
        getContentPane().add(editkelas);
        editkelas.setBounds(130, 100, 110, 30);

        jLabel4.setText("Alamat");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 140, 60, 14);
        getContentPane().add(editalamat);
        editalamat.setBounds(130, 140, 110, 30);

        Buttonproses.setText("Proses");
        Buttonproses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonprosesActionPerformed(evt);
            }
        });
        getContentPane().add(Buttonproses);
        Buttonproses.setBounds(140, 190, 80, 23);

        TAHasil.setColumns(20);
        TAHasil.setRows(5);
        jScrollPane1.setViewportView(TAHasil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 230, 220, 96);

        setSize(new java.awt.Dimension(416, 379));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editnamaActionPerformed

    private void editkelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editkelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editkelasActionPerformed

    private void ButtonprosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonprosesActionPerformed
        // TODO add your handling code here:
        String nama = editnama.getText();
        String kelas = editkelas.getText();
        String alamat = editalamat.getText();
        TAHasil.setText("Nama Siswa  : "+nama+"\n"+"Kelas Siswa  : "+kelas+"\n"+"Alamat Siswa : "+alamat+"\n");
    }//GEN-LAST:event_ButtonprosesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latiihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latiihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latiihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latiihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latiihan2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buttonproses;
    private javax.swing.JTextArea TAHasil;
    private javax.swing.JTextField editalamat;
    private javax.swing.JTextField editkelas;
    private javax.swing.JTextField editnama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
